### ISSUE TITLE
Plugin fails after LIFX update

### ISSUE THREAD

**Issue by koensayr** [autolog/LIFX_Controller#1]
It seems that after a recent update of the LIFX firmware, the plugin no longer controls the LIFX light strips. I'm able to auto detect them on the next work, but all status updates and action to turn them on fail. How can I got about helping to debug?

**Comment by autolog** [comment]
Are you running on the latest release 4.1.6 which is meant to address this issue?
What version of firmware are you running on your LIFX-Z?

**Comment by koensayr** [comment]
It does seem your update resolved the issue. My issue was that the plugin (and actually Indigo in general) doesn't seem to be able to update or notify one of updates when connecting with a remote client. Once I popped into the server directly, I had a nice reminder to update. Thank you and keep up the good work!
