### ISSUE TITLE
Two devices stuck in starting

### ISSUE THREAD

**Issue by blueatria** [autolog/LIFX_Controller#4]
I have two devices stuck in starting state. One is a A19 blue and one is a downlight. Both have good wifi strength and are controllable by the app no problem. I updated the plugin to 6.0.12 with no change. Here is the log entry

============================================== Initialising LIFX Controller Plugin ===============================================
Plugin Name:                    LIFX
Plugin Version:                 6.0.12
Plugin ID:                      com.autologplugin.indigoplugin.lifxcontroller
Indigo Version:                 7.5.0
Indigo API Version:             2.4
Python Version:                 2.7.16 (default, Jun  5 2020, 22:59:21) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
Mac OS Version:                 10.15.7
==================================================================================================================================

   LIFX                            Logging to Indigo Event Log at the 'Info' level
   LIFX                            Logging to LIFX Plugin Log at the 'Info' level
   Started plugin "LIFX 6.0.12"
   LIFX                            'LIFX Controller' giving Discovery an opportunity to complete . . .
   LIFX                            LIFX device discovery starting (this can take up to 60 seconds) . . .
   LIFX Error                      LIFXLAN [discover_devices] discovered an unknown LIFX device with product code: '70'. Device's MAC is 'd0:73:d5:5a:89:15' and IP Address is '192.168.86.163'. Plugin is unable to manage this device. Please report this on the support forum.
   LIFX                            

LIFX device discovery has completed. 10 LIFX device(s) have been discovered as follows:

Start of discovered LIFX devices list ---->
  'Beam'        [d0:73:d5:27:d8:bf] at 192.168.86.20
  'Dining Room' [d0:73:d5:25:9e:23] at 192.168.86.84
  'Kitchen'     [d0:73:d5:28:65:35] at 192.168.86.175
  'Lounge Room' [d0:73:d5:28:53:ad] at 192.168.86.122
  'TV 1'        [d0:73:d5:32:5f:82] at 192.168.86.252
  'TV 2'        [d0:73:d5:32:5d:05] at 192.168.86.73
  'Terrace 1'   [d0:73:d5:27:b3:03] at 192.168.86.133
  'Terrace 2'   [d0:73:d5:27:29:99] at 192.168.86.215
  'Terrace 3'   [d0:73:d5:27:bb:ea] at 192.168.86.180
  'Terrace 4'   [d0:73:d5:27:af:9d] at 192.168.86.96
<---- End of discovered LIFX devices list.

   LIFX                            . . . 'LIFX Controller' initialization now completed.
   LIFX                            Starting  'Beam' . . . 
   LIFX                            . . . Started 'LIFX LIFX Beam' device: 'Beam'.
   LIFX                            Starting  'Dining Room' . . . 
   LIFX                            . . . Started 'LIFX LIFX A19' device: 'Dining Room'.
   LIFX                            Starting  'Kitchen' . . . 
   LIFX                            . . . Started 'LIFX LIFX A19' device: 'Kitchen'.
   LIFX                            Starting  'Lounge Room' . . . 
   LIFX Warning                    Having trouble accessing LIFX device 'Lounge Room' with MAC address 'd0:73:d5:28:53:ad' at IP address '192.168.86.12 . . .
   LIFX Warning                    . . . Trying again to access 'Lounge Room' . . .
   LIFX Warning                    . . . Trying again to access 'Lounge Room' . . .
   LIFX Warning                    . . . Trying again to access 'Lounge Room' . . .
   LIFX Warning                    . . . Trying again to access 'Lounge Room' . . .
   LIFX Warning                    . . . Trying again to access 'Lounge Room' . . .
   LIFX Error                      . . . Giving up! Failed to access LIFX device 'Lounge Room' with MAC address 'd0:73:d5:28:53:ad' at IP address '192.168.86.12
   LIFX                            Starting  'Terrace 1' . . . 
   LIFX                            . . . Started 'LIFX LIFX Downlight' device: 'Terrace 1'.
   LIFX                            Starting  'Terrace 2' . . . 
   LIFX                            . . . Started 'LIFX LIFX Downlight' device: 'Terrace 2'.
   LIFX                            Starting  'Terrace 3' . . . 
   LIFX                            . . . Started 'LIFX LIFX Downlight' device: 'Terrace 3'.
   LIFX                            Starting  'Terrace 4' . . . 
   LIFX Warning                    Having trouble accessing LIFX device 'Terrace 4' with MAC address 'd0:73:d5:27:af:9d' at IP address '192.168.86.3 . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   LIFX Warning                    . . . Trying again to access 'Terrace 4' . . .
   LIFX Error                      . . . Giving up! Failed to access LIFX device 'Terrace 4' with MAC address 'd0:73:d5:27:af:9d' at IP address '192.168.86.3
   LIFX                            Starting  'TV 1' . . . 
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   LIFX                            . . . Started 'LIFX LIFX Mini White' device: 'TV 1'.
   LIFX                            Starting  'TV 2' . . . 
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 1
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 2
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 2
   LIFX                            . . . Started 'LIFX LIFX Mini White' device: 'TV 2'.
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteTemperature for device TV 2
   Error                           updateStateOnServer() caught exception: LowLevelBadParameterError -- invalid color level key whiteLevel for device TV 2

This also has the other error that I comment on in the other issue I updated.

Any thoughts?

**Comment by blueatria** [comment]
Ok I see that the IP address being reported is wrong. Is this cached somewhere?

**Comment by autolog** [comment]
I will look at this in more detail after the Christmas holiday break.

The message "LIFX Error LIFXLAN [discover_devices] discovered an unknown LIFX device with product code: '70'. " is a LIFX Switch which is not supported by the plugin.

What should the IP address be?

**Comment by blueatria** [comment]
Sorry I found that I can change the ip address on the device in indigo. I am curious as to why this occurs? No big deal but does not discovery look for the correct ip? When ever you can look at it is fine. Have a good holiday. 

The error about the unknown device is the Lifx switch I already asked you about. Seems there some doc now on the switch https://lan.developer.lifx.com/docs/the-lifx-switch. Does not look like it is implemented in lifxlan python module.

**Comment by autolog** [comment]
It was a bug. I was checking for a changed IP address but too late in the code sequence. I have pushed a new release 6.0.14 to the Indigo Plugin Store.

I won't be supporting LIFX Switches until the lifxlan library supports it and/or the product becomes available in the UK.

Thanks for reporting the error. :)
