### ISSUE TITLE
New LIFX Z LED Light Strips Will not Discover

### ISSUE THREAD

**Issue by pgpappas** [autolog/LIFX_Controller#6]
I recently added 2 new LIFX Z light strips that will not auto discover. All my other previous LIFX lights, including other LIFX Zs work correctly. Just the two new light strips won't discover. Probably unrelated, I have 7 LIFX Smart 2 button Switches that also won't discover.
The LIFX Zs are: 
MAC: d0:73:d5:6e:48:3e  LIFX Z Living Room TV Shelf SN: D073D56E483D
MAC: d0:73:d5:6d:f7:02 LIFX Z TV Cabinet-Left SN: D073D56DF701

Three of the seven LIFX Switches also show in the Warning Log. See LIFX Warning and event log below.

======================================= Initialising LIFX Controller Bridge Plugin Plugin ========================================
Plugin Name:                    LIFX
Plugin Version:                 2022.0.1
Plugin ID:                      com.autologplugin.indigoplugin.lifxcontroller
Indigo Version:                 2022.1.2
Indigo License:                 ActiveSubscription
Indigo API Version:             3.1
Architecture:                   x86_64
Python Version:                 3.10.2 (v3.10.2:a58ebcc701, Jan 13 2022, 14:50:16) [Clang 13.0.0 (clang-1300.0.29.30)]
Mac OS Version:                 13.1
==================================================================================================================================

   LIFX                            Logging to Indigo Event Log at the 'Info' level
   LIFX                            Logging to LIFX Plugin Log at the 'Warning' level
   Started plugin "LIFX 2022.0.1"
   LIFX                            LIFX device discovery starting (this can take up to 60 seconds) . . .
   LIFX                            Initialising to poll at 300.0 second intervals
   LIFX                            'LIFX Controller' giving Discovery an opportunity to complete . . .
   LIFX Warning                    LIFXLAN [discover_devices] discovered an unknown LIFX device with product code: '117'. Device's MAC is 'd0:73:d5:6e:48:3d' and IP Address is '192.168.1.167'. Plugin is unable to manage this device. Please report this on the support forum.
   LIFX Warning                    LIFXLAN [discover_devices] discovered an unknown LIFX device with product code: '116'. Device's MAC is 'd0:73:d5:6c:50:b9' and IP Address is '192.168.1.166'. Plugin is unable to manage this device. Please report this on the support forum.
   LIFX Warning                    LIFXLAN [discover_devices] discovered an unknown LIFX device with product code: '116'. Device's MAC is 'd0:73:d5:6c:33:57' and IP Address is '192.168.1.162'. Plugin is unable to manage this device. Please report this on the support forum.
   LIFX Warning                    LIFXLAN [discover_devices] discovered an unknown LIFX device with product code: '117'. Device's MAC is 'd0:73:d5:6d:f7:01' and IP Address is '192.168.1.168'. Plugin is unable to manage this device. Please report this on the support forum.
   LIFX Warning                    LIFXLAN [discover_devices] discovered an unknown LIFX device with product code: '116'. Device's MAC is 'd0:73:d5:6c:4f:de' and IP Address is '192.168.1.160'. Plugin is unable to manage this device. Please report this on the support forum.
   LIFX                            

LIFX device discovery has completed. 9 LIFX device(s) have been discovered as follows:

Start of discovered LIFX devices list ---->
  'Hall Sconce 2'          [MAC d0:73:d5:32:e0:92] at IP '192.168.1.144'. Product 49: LIFX Mini Color
  'TV Cabinet LIFX Z'      [MAC d0:73:d5:26:a4:c9] at IP '192.168.1.130'. Product 32: LIFX Z
  'Theater Ceiling 2'      [MAC d0:73:d5:26:1a:58] at IP '192.168.1.146'. Product 28: LIFX BR30
  'Theater Ceiling 3'      [MAC d0:73:d5:26:36:0b] at IP '192.168.1.147'. Product 28: LIFX BR30
  'Theater Curtain Lights' [MAC d0:73:d5:27:3b:95] at IP '192.168.1.159'. Product 32: LIFX Z
  'Theater Sconce 1'       [MAC d0:73:d5:32:e2:bb] at IP '192.168.1.136'. Product 49: LIFX Mini Color
  'Theater Sconce 2'       [MAC d0:73:d5:32:c0:d6] at IP '192.168.1.137'. Product 49: LIFX Mini Color
  'Theater Sconce 3'       [MAC d0:73:d5:33:06:bc] at IP '192.168.1.138'. Product 49: LIFX Mini Color
  'Theater Sconce 4'       [MAC d0:73:d5:33:08:02] at IP '192.168.1.139'. Product 49: LIFX Mini Color
<---- End of discovered LIFX devices list.

   LIFX                            . . . 'LIFX Controller' initialization now completed.
   LIFX                            Starting  'Hall Cabinet LIFX Z' . . . 
   LIFX                            . . . Started 'LIFX LIFX Z' device: 'Hall Cabinet LIFX Z'.
   LIFX                            Starting  'Hall Sconce 1' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Hall Sconce 1'.
   LIFX                            Starting  'Hall Sconce 2' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Hall Sconce 2'.
   LIFX                            Starting  'Kitchen Cabinets LIFX Z' . . . 
   LIFX                            . . . Started 'LIFX LIFX Z' device: 'Kitchen Cabinets LIFX Z'.
   LIFX                            Starting  'Kitchen Ceiling 1' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 1'.
   LIFX                            Starting  'Kitchen Ceiling 10' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 10'.
   LIFX                            Starting  'Kitchen Ceiling 2' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 2'.
   LIFX                            Starting  'Kitchen Ceiling 3' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 3'.
   LIFX                            Starting  'Kitchen Ceiling 4' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 4'.
   LIFX                            Starting  'Kitchen Ceiling 5' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 5'.
   LIFX                            Starting  'Kitchen Ceiling 6' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 6'.
   LIFX                            Starting  'Kitchen Ceiling 7' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 7'.
   LIFX                            Starting  'Kitchen Ceiling 8' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 8'.
   LIFX                            Starting  'Kitchen Ceiling 9' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Kitchen Ceiling 9'.
   LIFX                            Starting  'Kitchen Sconce 1' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Kitchen Sconce 1'.
   LIFX                            Starting  'Kitchen Sconce 2' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Kitchen Sconce 2'.
   LIFX                            Starting  'Kitchen Sconce 3' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Kitchen Sconce 3'.
   LIFX                            Starting  'Living Room TV Cabinet LIFX Z' . . . 
   LIFX                            . . . Started 'LIFX LIFX Z' device: 'Living Room TV Cabinet LIFX Z'.
   LIFX                            Starting  'Parrot Bathroom' . . . 
   LIFX                            . . . Started 'LIFX LIFX Z' device: 'Parrot Bathroom'.
   LIFX                            Starting  'Theater Ceiling 1' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Theater Ceiling 1'.
   LIFX                            Starting  'Theater Ceiling 2' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Theater Ceiling 2'.
   LIFX                            Starting  'Theater Ceiling 3' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Theater Ceiling 3'.
   LIFX                            Starting  'Theater Ceiling 4' . . . 
   LIFX                            . . . Started 'LIFX LIFX BR30' device: 'Theater Ceiling 4'.
   LIFX                            Starting  'Theater Curtain Lights' . . . 
   LIFX                            . . . Started 'LIFX LIFX Z' device: 'Theater Curtain Lights'.
   LIFX                            Starting  'Theater Sconce 1' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Theater Sconce 1'.
   LIFX                            Starting  'Theater Sconce 2' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Theater Sconce 2'.
   LIFX                            Starting  'Theater Sconce 3' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Theater Sconce 3'.
   LIFX                            Starting  'Theater Sconce 4' . . . 
   LIFX                            . . . Started 'LIFX LIFX Mini Color' device: 'Theater Sconce 4'.

**Comment by autolog** [comment]
Thanks for the report.

I have updated the plugin with the latest LIFX products.

A pre-release version is available here: [LIFX Controller V_2022.0.4](https://github.com/autolog/LIFX_Controller/releases/tag/2022.0.4)

Let me know if that fixes the discovery problem.

The plugin only supports LIFX lights, not LIFX switches.

**Comment by pgpappas** [comment]
The pre-release version fixed the discovery issue. I know the plugin only supports lights at this time. Do you think support for switches can be added in the future? I need the terminal contacts on the switches to be exposed to Indigo in order to control non-LIFX devices hard wired to the switch.
Thank your for providing this fix.

**Comment by autolog** [comment]
Thanks for letting me know it works. I will relaese it to the Indigo Plugin Store.

The problem with LIFX Switches are twofold: 1) the underlying LIFXLAN library I use doesn't support them and 2) You can't get them in the UK. If the situation changes, I will review what can be done in the plugin.
